data = [
    {"text": "1.Does subject have poor eye contact ?"},
    {"text": "2.Is subject Inappropriately anxious, scared ?"},
    {"text": "3.Does subject have Lack of curiosity about the environment ?"},
    {"text": "4.Does Subject Inappropriately cry or laugh ?"},
    {"text": "5.Does Subject Hates crowds ?"},
    {"text": "6.Does Subject Lack ability to imitate ?"},
    {"text": "7.Does Subject Produces unusual noises ?"},
    {"text": "8.Can subjetc sustain conversation ?"},
    {"text": "9.Does Subject Speaks same to kids, adults, objects (can not differentiate) ?"},
    {"text": "10.Does Subject is Stubborn about rituals and routines; resists to change ?"},
    {
        "text": "Age of child (in years)",
        "type": "number",
        "input": {"step": 1, "min_value": 2},
    },
    {
        "text": "Gender",
        "type": "select",
        "options": ("Male", "Female"),
    },
    {
        "text": "Ethnicity",
        "type": "select",
        "options": (
            "Middle Eastern",
            "Black",
            "White European",
            "Asian",
            "South Asian",
            "Others",
            "Pacifica",
            "Middle Eastern",
            "Mixed",
        ),
    },
    {"text": "Jaundice at birth"},
    {
        "text": "Relation who took the test",
        "type": "select",
        "options": (
            "Parent",
            "Relative",
            "Self",
            "Health care professional",
            "Others",
        ),
    },
    {"text": "Autism in blood relations"},
    {
        "text": "Age description",
        "type": "select",
        "options": ("Toddler", "Child", "Teenager", "Adult"),
    },
]
