data = [
    {"text": "1)Poor eye contact, or staring from unusual angle"},
    {"text": "2)Inappropriately anxious, scared"},
    {"text": "3)Lack of curiosity about the environment"},
    {"text": "4)Inappropriate crying or laughing"},
    {"text": "5)Hates crowds, difficulties in restaurants and supermarkets"},
    {"text": "6)Lack of ability to imitate"},
    {"text": "7)Produces unusual noises or infantile squeals"},
    {"text": "8)Can not sustain conversation"},
    {"text": "9)Speaks same to kids, adults, objects (can not differentiate)"},
    {"text": "10)Stubborn about rituals and routines; resists to change"},
    {
        "text": "Age of child (in years)",
        "type": "number",
        "input": {"step": 1, "min_value": 2},
    },
    {
        "text": "Gender",
        "type": "select",
        "options": ("Male", "Female"),
    },
    {
        "text": "Ethnicity",
        "type": "select",
        "options": (
            "Middle Eastern",
            "Black",
            "White European",
            "Asian",
            "South Asian",
            "Others",
            "Pacifica",
            "Middle Eastern",
            "Mixed",
        ),
    },
    {"text": "Jaundice at birth"},
    {
        "text": "Relation who took the test",
        "type": "select",
        "options": (
            "Parent",
            "Relative",
            "Self",
            "Health care professional",
            "Others",
        ),
    },
    {"text": "Autism in blood relations"},
    {
        "text": "Age description",
        "type": "select",
        "options": ("Toddler", "Child", "Teenager", "Adult"),
    },
]
